# -*- coding: utf-8 -*-
"""CatBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mo5pU5DkITb7DuIfvGAZohUom3lbGA-V
"""

!pip install catboost

# STEP 3: Import libraries
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from catboost import CatBoostClassifier

df = pd.read_csv('/content/catboost_sample.csv')
df.head()

num_cols = ['fare', 'age']
imputer = KNNImputer(n_neighbors=5)
df[num_cols] = imputer.fit_transform(df[num_cols])

# Categorical: Fill with mode
cat_cols = ['sex', 'embarked', 'embark_town', 'class']
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# STEP 6: Encode categorical variables
for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# STEP 7: Train-test split
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# STEP 8: Train CatBoost Classifier
model = CatBoostClassifier(verbose=0)  # Suppress training output
model.fit(X_train, y_train)

# STEP 9: Evaluate model
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

