# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Zb3WomPNbg7l5CrywlxLAgOK1Qm-oYr
"""

import pandas as pd

from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

##  code for model

df=pd.read_csv('/content/500hits.csv',encoding='latin-1')

df.head()

df=df.drop(columns=['PLAYER','CS'])

df.head()

X=df.iloc[:,0:13]

y=df.iloc[:,13]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=11)

scaler=MinMaxScaler(feature_range=(0,1))

X_train=scaler.fit_transform(X_train)

X_test=scaler.fit_transform(X_test)

knn = KNeighborsClassifier(n_neighbors=8)

knn.fit(X_train,y_train)

y_pred=knn.predict(X_test)

print(y_pred)

knn.score(X_test,y_test)

cm=confusion_matrix(y_test,y_pred)

print(cm)

cr=classification_report(y_test,y_pred)

print(cr)

print(classification_report(y_test,y_pred))

print(knn.n_samples_fit_)

